exception.id_not_found=La ID: {0} no se encontró ninguna tarea pendiente.